### ISSUE TITLE
Skip opcache enabled check for initial preload

### ISSUE THREAD

**Issue by oojacoboo** [DarkGhostHunter/Preloader#18]
```
Message: Opcache is disabled. No preload script can be generated.
```

For us, the preload generator is within our bootstrapping which is called during every request in our dev environment.  This is, of course, included in the preload since it's part of the bootstrapping.  The issue is that opcache isn't available during the initial PHP preload, during boot.  Therefore, it throws this error.

It'd be great if there was a way to check to see if the `require_once` call is being initiated during a preload event, or a normal php process.

**Comment by oojacoboo** [comment]
I guess an alternative here, and maybe the appropriate one, is to check if it's enabled within our boot process and execute the generator or not.  In fact, I'm sure this is the best angle.  I'm closing this ticket.

**Comment by DarkGhostHunter** [comment]
> I guess an alternative here, and maybe the appropriate one, is to check if it's enabled within our boot process and execute the generator or not. In fact, I'm sure this is the best angle. I'm closing this ticket.

Was gonna point that. The Preloader is pretty much useless without opcache. If when called is not enabled, then is just better to not call it.
