### ISSUE TITLE
opcache_compile_file vs require_once

### ISSUE THREAD

**Issue by oojacoboo** [DarkGhostHunter/Preloader#2]
First of all, thanks for the awesome preloader here.  I really like the approach you've taken.  I am curious about the decision to use `require_once` instead of `opcache_compile_file`.  Is there a fundamental difference between the two, or are they both cached with opcache similarly?

**Comment by DarkGhostHunter** [comment]
AFAIK, `opcache_compile_file` will compile alone, but not its linked files, like traits, interfaces, or extended classes, among others, so you will have to compile these dependencies first.

`require_once` return the file with these links, avoiding partially preloading a file. Using the Autoloader, `require_once` can safely bring these links into PHP.

**Comment by oojacoboo** [comment]
Yea, that's nice and a good point.  I was reading the following article, which left me a bit confused about the opcache files on disk vs memory and opcodes vs possibility of preloading being bytecode.

https://stitcher.io/blog/preloading-in-php-74

I had another discussion about this on IRC.  I'm guessing this author really misstated things here and that there isn't any real difference in effect at the opcache level.

**Comment by DarkGhostHunter** [comment]
> Yea, that's nice and a good point. However, I don't think the affect is the same. Running `require_once` on these files would only warm up opcache for a new instance. 

New instance of what? Creating a class? Care to elaborate? The only difference the article says, is that require will also take in other dependant files.

> After using this preload file and another preload composer plugin, anecdotally, I noticed that this isn't providing me any speed benefits, while the other preload offered noticeably faster page load times.

What plugin? What files? How it preloads? What benchmarks? How you tested?

**Comment by oojacoboo** [comment]
@DarkGhostHunter please see the updated post.  You must be replying from email.

**Comment by DarkGhostHunter** [comment]
I think I should make some benchmarks. For what I have read in the RFC, preloading should better than just letting Opcache cache the files on requests.

 > Preloading is implemented as a part of the opcache on top of another (already committed) patch that introduces “immutable” classes and functions. They assume that the immutable part is stored in shared memory once (for all processes) and never copied to process memory, but the variable part is specific for each process. The patch introduced the MAP_PTR pointer data structure, that allows pointers from SHM to process memory.

We should make some benchmarks to compare: preloading everything, priority preload (my approach), cold opcache (no preload), no opcache.

**Comment by oojacoboo** [comment]
@DarkGhostHunter That'd be awesome.  At this point, I'm assuming that it's using the same opcache and the only difference is that `require_once` actually executes the code where `opcache_compile_file` does not execute it and only loads in that file.

**Comment by DarkGhostHunter** [comment]
Well, the opcache_compile_file won't be an option anymore since I just figured out the list may be sliced just before a file is linked to another outside it. Using require will allow the autoloader to require that file automatically inside the list, while the other won't and will left it out along a nice warning when starting up.

I'm closing this because these limitations. Meanwhile, the user is free to use that function to preload manually its own list of files.

**Comment by rulatir** [comment]
If a class is preloaded with `opcache_compile_file($file_that_contains_class)`, is it true that the `class_exists()` from that point on, or should the file containing it still be `require`d (resulting in opcache hit)?

**Comment by DarkGhostHunter** [comment]
> If a class is preloaded with `opcache_compile_file($file_that_contains_class)`, is it true that the `class_exists()` from that point on, or should the file containing it still be `require`d (resulting in opcache hit)?

From what I know, it will only for what is declared inside, like a class. If there is a reference to a class/interface/trait or whatever, it won't be resolved at preloading.
