### ISSUE TITLE
Yaml files included

### ISSUE THREAD

**Issue by oojacoboo** [DarkGhostHunter/Preloader#20]
The preloader is currently attempting to require tons of yaml files.  I'm sure it's due to some legacy framework stuff, but I do not have any way to effectively exclude these.

If a recursive glob was supported I could easily do, `/path/to/web/root/**/*.yml`.

**Comment by DarkGhostHunter** [comment]
The Preloader gets the list from the Opcache list. If your Opcache is also listing YAML files, these will show up into Preloader. If you're using `append()`, you should use something like `/app/quz/*.php`.

Currently I'm busy to add a recursive glob to Preloader. Any kind of help would be appreciated if you want it ASAP, or you can wait for me.
