### ISSUE TITLE
Wrong parameter `shouldRequire()`

### ISSUE THREAD

**Issue by aksafan** [DarkGhostHunter/Preloader#27]
@DarkGhostHunter hello,

I have tried your library and this config param `[shouldRequire()](https://github.com/DarkGhostHunter/Preloader#shouldrequire)` makes me stunned a bit, cause there are no such property or method in your source code. Instead, there is another one, called `[useRequire()](https://github.com/DarkGhostHunter/Preloader/blob/master/src/GeneratesScript.php#L49 )` and the same property.
Think, this is only the naming bug in the doc. Would be nice if you fix it, so another guys won't be like me))

Thank you!

**Comment by DarkGhostHunter** [comment]
> Think, this is only the naming bug in the doc.

You got that right. Fixing in `master`. Usually I push to `stable` along other features, fixes or else.

**Comment by DarkGhostHunter** [comment]
Fixed in [commit](https://github.com/DarkGhostHunter/Preloader/commit/edcbe261877288f6d18284a546f91f1230526f66). Thanks.

**Comment by DarkGhostHunter** [comment]
BTW, don't be shy to issue a PR youself.

**Comment by aksafan** [comment]
> 
> 
> Fixed in [commit](https://github.com/DarkGhostHunter/Preloader/commit/edcbe261877288f6d18284a546f91f1230526f66). Thanks.

Thank you!



> 
> 
> BTW, don't be shy to issue a PR youself.

It was 3 am here, when I realize what is wrong, so was not in condition to make good PR =)
But in future -  yeah
