### ISSUE TITLE
symfony/finder is required as dev but should be for all envs

### ISSUE THREAD

**Issue by steevanb** [DarkGhostHunter/Preloader#30]
Hi,

Thanks for your awesome tool!
I'm trying to integrate it into phpbenchmarks.com benchmark kit, to help us creating the preload script for PHP 7.4 benchmarks.

I think there is a little mistake in `composer.json` : `symfony/finder` is required only for `dev`, but is used into `ManagesFiles` (it should be `ManageFiles`, without `s`, no ?).

`symfony/finder` should be required for all envs no?

`2020/03/29 18:46:21 [error] 1389#1389: *405 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Finder\Finder' not found in /var/www/phpbenchmarks/project/generator/var/generator/5e80978c2d086/generated/vendor/darkghosthunter/preloader/src/ManagesFiles.php:81`

**Comment by DarkGhostHunter** [comment]
Oh gawd you're right. Gonna push asap.

**Comment by DarkGhostHunter** [comment]
Fixed in 2.0.2.

https://github.com/DarkGhostHunter/Preloader/releases/tag/v2.0.2

**Comment by steevanb** [comment]
Thanks!
