### ISSUE TITLE
I can't exclude files with exclude()

### ISSUE THREAD

**Issue by steevanb** [DarkGhostHunter/Preloader#33]
With this code:
```
DarkGhostHunter\Preloader\Preloader::make()
    ->selfExclude()
    ->exclude("$sourceCodePath/public/phpbenchmarks_preloader_generator.php")
    ->writeTo('...');
```
I have this error:
`2020/03/30 16:27:56 [error] 5091#5091: *177 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "/var/www/phpbenchmarks/project/generator/var/generator/5e81fd32ac643/generated/public/phpbenchmarks_preloader_generator.php" directory does not exist. in /var/www/phpbenchmarks/project/generator/var/generator/5e81fd32ac643/generated/vendor/symfony/finder/Finder.php:589`

So we can't exclude files from the list, only directories?

**Comment by DarkGhostHunter** [comment]
Yes, buy you can pass a Closure to filter further the files of your directories.

**Comment by steevanb** [comment]
Good idea, thanks!
