### ISSUE TITLE
Change the base dir

### ISSUE THREAD

**Issue by steevanb** [DarkGhostHunter/Preloader#34]
Hi,

I have this file structure:

* /var
  * /www
    * /public
      * index.php
    * /preload
      * preload.php
      * preload_generator.php
    * /src
      * Foo.php

When i generate a preload file from `/var/www/preload/preload_generator.php` with :
```php
DarkGhostHunter\Preloader\Preloader::make()
    ->selfExclude()
    ->writeTo(__DIR__ . '/preload.php');
```

File paths contains `/var/www`, like this:
```php
$files = [
    '/var/www/public/index.php',
    '/var/www/src/Normalizer/ObjectToSerializeNormalizer.php'
];
```

Problem is: I can't commit this preload file because if somebody install my project in another directory than `/var/www`, preload script will not work.

To solve it maybe you can add `replaceInPath('/var/www', '../')`:
```php
$files = [
    '../public/index.php',
    '../src/Foo.php'
];
```

**Comment by DarkGhostHunter** [comment]
```
$files = [
    __DIR__ . '/../public/index.php',
    __DIR__ . '/../src/Foo.php'
];
```

**Comment by steevanb** [comment]
Seems cool to have it, but I don't understand how can i have it?
