### ISSUE TITLE
Number of files being required

### ISSUE THREAD

**Issue by oojacoboo** [DarkGhostHunter/Preloader#4]
How is the preloader determining the number of files to be required?  I realize it's getting the files with the most opcache hits, but how is that being calculated?   I'd really like for the preloader to load in a lot more files.

**Comment by DarkGhostHunter** [comment]
> How is the preloader determining the number of files to be required? I realize it's getting the files with the most opcache hits, but how is that being calculated? I'd really like for the preloader to load in a lot more files.

The file limit is given by a memory limit. Each cached file reported by Opcache has a script memory consumption. Preloader will [create a list until of the most requested files until it reaches the memory limit](https://medium.com/@DarkGhostHunter/preloading-your-php-7-4-project-in-one-line-9ede756f292c).

It could have a list limit in files, but I don't see any clear advantage doing that.
