### ISSUE TITLE
php 8 and composer

### ISSUE THREAD

**Issue by oitsuki** [DarkGhostHunter/Preloader#45]
Hello,
I installed php 8 and when I run composer on your application I have an error nd do accept to make an update (or look) but you app seems to work fine in php 8.0

**Comment by danijelk** [comment]
#46

**Comment by DarkGhostHunter** [comment]
https://github.com/DarkGhostHunter/Preloader/commit/b98849c7a2d54a0e60dcf7b9aaa08ad40b74d01c
