### ISSUE TITLE
can work without restart web-server

### ISSUE THREAD

**Issue by mj2ks** [DarkGhostHunter/Preloader#51]
steps on first run:
1. save filelist after generate;
2. aplly changes;

steps on next generate:
0. load old filelist and invalidate files use opcache_invalidate($file, true);
go to 1.

may be better invalidate diff old of new filelist and compile diff new of old filelist

how do you like the idea?

**Comment by DarkGhostHunter** [comment]
Seems really cool to avoid restarting the server. Is your claim backed?

PD: `opcache_reset()` it's better IMO.
