### ISSUE TITLE
Understanding reason for suggesting this be part of your application lifecycle

### ISSUE THREAD

**Issue by garygreen** [DarkGhostHunter/Preloader#52]
Great library here! Though I'm curious to know why conditions have been implemented and why the readme suggests this be included as part of your application lifecycle.

* Using `when` or `whenOneIn` as part of a request lifecycle surely that would impact users based on the lottery and has potential to interfere with the request?
* FPM/PHP needs to be reloaded - if that's the case you couldn't do this as part of the request, so the thing that initiates the preloader and thing that activates it are different which is kind of weird
* This library uses OpCache stats - this means it has access globally to all the opcached files for every PHP FPM pool. It doesn't matter whether you preload as part of a request lifecycle - you could just have it in a bog standard `php` file that purely preloads. The example in your readme makes it look like it's suggested to be included as part of your app `require __DIR__ . '/../vendor/autoload.php';`

Would it make more sense to have a bog standard preload script:

**preload-af8d68a6e897ef78ad78.php**
```
<?php
use DarkGhostHunter\Preloader\Preloader;

Preloader::make()
    ->memoryLimit(64)
    ->writeTo(PHP_LOCALSTATEDIR . '/preload.php'); // put it in /var.;
```

...which is called part of a cron task (say, every other day) which then reloads fpm gracefully:

```
curl https://my-app.com/preload-af8d68a6e897ef78ad78.php && service php-fpm reload
```

Would that work? Surely that is simpler than including it as part of your application lifecycle, using conditions, plus it activates it straight away and seems safer in that it avoids any potential to interfere with requests?

Just trying to understand the reasoning for having the suggested usage so tied into your application. Seems to me that something that is for optimizing production code shouldn't really be included every single request.

**Comment by DarkGhostHunter** [comment]
> * Using `when` or `whenOneIn` as part of a request lifecycle surely that would impact users based on the lottery and has potential to interfere with the request?

They're just for convenience. Saves you an `if` if you're dealing with something that can be truthy or falsy. Otherwise, you can do you own condition.

> * FPM/PHP needs to be reloaded - if that's the case you couldn't do this as part of the request, so the thing that initiates the preloader and thing that activates it are different which is kind of weird

Your app is already warmed. It's the next startup which will start cold. The preload list avoids that.

> * This library uses OpCache stats - this means it has access globally to all the opcached files for every PHP FPM pool. It doesn't matter whether you preload as part of a request lifecycle - you could just have it in a bog standard `php` file that purely preloads. The example in your readme makes it look like it's suggested to be included as part of your app `require __DIR__ . '/../vendor/autoload.php';`

The autoloader is needed to resolve files if you use `require`. Not recommend if you have files with direct execution statements.

> * Would it make more sense to have a bog standard preload script:
> 
> **preload-af8d68a6e897ef78ad78.php**

Good idea. A preload file would call another with the actual list, or do nothing if it doesn't exists. May be in the next major versions.

> ```
> <?php
> use DarkGhostHunter\Preloader\Preloader;
> 
> Preloader::make()
>     ->memoryLimit(64)
>     ->writeTo(PHP_LOCALSTATEDIR . '/preload.php'); // put it in /var.;
> ```
> 
> ...which is called part of a cron task (say, every other day) which then reloads fpm gracefully:
> 
> ```
> curl https://my-app.com/preload-af8d68a6e897ef78ad78.php && service php-fpm reload
> ```
> 
> Would that work? Surely that is simpler than including it as part of your application lifecycle, using conditions, plus it activates it straight away and seems safer in that it avoids any potential to interfere with requests?

Cannot get the source of truth from outside the very own process where opcache is running. In my opinion, this is over-engineering.

> Just trying to understand the reasoning for having the suggested usage so tied into your application. Seems to me that something that is for optimizing production code shouldn't really be included every single request.

It has to. If it's not tied to the process itself, then no order list can be truthfully generated. And is the same PHP process that needs to preload (warm) these files.

**Comment by garygreen** [comment]
@DarkGhostHunter 

> Good idea. A preload file would call another with the actual list, or do nothing if it doesn't exists.

I'm not sure your understanding what I'm getting at here though.

Your correct that this needs to run within the context of where the opcache is running. Which means you cannot get it if you use a console command, etc. However, as long as you run in the context of any PHP FPM pool - you'll get the full list of opcached files. This is because OpCache is shared amongst all the pools and various PHP processes. This means if you ran a Laravel + Wordpress + Magento site on your server - you'd get a list of all those opcached files, regardless of user and what framework you used to get the list. That's just the way OpCache works - it's shared memory that doesn't need to *specifically* run within the context of a specific framework.

You could even have this preload script running on a different domain which runs Drupal (but on the same server) and you could still get the list of opcached Laravel files. Try it - get the list of opcached files outside of a Laravel application but running on same server. Even try it on a different domain.

So that's why I'm a bit baffled why it's suggested this be run as part of your application lifecycle. That just seems risky and totally not necessary. It should be isolated as a separate thing that gets run. Which is why I asked about conditions etc... because having any kind of condition encourages it to be used as part of your application lifecycle.

This preload script is for your WHOLE server. It's not just your application, but everything that runs on your server using shared OpCache memory. So it makes more sense to have it as a standalone script.

**Comment by DarkGhostHunter** [comment]
Can't run outside the context it wants to preload. An alternative may be creating a filter with `getList()` to only include what you want.

Using shared servers for critical applications or one PHP for multiple critical applications is bad design IMO and you should avoid it.

Currently I'm not interested in changing how the package works, but it may in the future.

**Comment by garygreen** [comment]
> Can't run outside the context it wants to preload. An alternative may be creating a filter with getList() to only include what you want.

It can. See the attached screenshot - this is a seperate PHP file that doesn't run Laravel or composer at all. All it has is:

```php
<?php
print_r(opcache_get_status(true));
````

![image](https://user-images.githubusercontent.com/1702638/133807648-3e38b2fc-882d-4c0c-9628-b1bd7c7c3986.png)

Even though it's not running within Laravel - it can see all the shared OpCache files. It even sees PHPMyAdmin. It sees all the shared OpCache pool files from all users.

So this preloader should really be standalone. It doesn't need to be incorporated into your app.
